install:
  - SET PATH=C:/Ruby%ruby_version%/bin;%PATH%
  - SET PATH=C:/MinGW/msys/1.0/bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - ruby --version
  - gem --version
  - bundle install

  # When running ruby-x86, we make use of the softokn3.dll that is part of the
  # pre-installed firefox. The test helper will find it automatically.
  # When running ruby-x64, we equally need a 64 bit softokn3.dll to test against.
  # However it is not part of any installed software on appveyor, nor is it
  # officially released as a windows binary, so we download and install a 64 bit
  # firefox version and use it's softokn3.dll.
  - ps: |
        $ErrorActionPreference = "Stop" # "set -e"
        if ($env:isx64 -eq "1")
        {
          $(new-object net.webclient).DownloadFile('http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/40.0b4/win64/en-US/Firefox%20Setup%2040.0b4.exe', 'C:/firefox-setup.exe')
          dir "C:/"
          cmd /c "C:\firefox-setup.exe"
          dir "C:/Program Files/"
          $env:SOFTOKN_PATH = 'C:/Program Files/Mozilla Firefox/softokn3.dll'
          $env:PATH = 'C:/Program Files/Mozilla Firefox;' + $env:PATH
          dir "C:/Program Files/Mozilla Firefox/"
        }

build: off

test_script:
  - bundle exec rake compile test gem

environment:
  matrix:
    - ruby_version: "25-x64"
      RUBY_DLL_PATH: "C:/Program Files/Mozilla Firefox"
      isx64: "1"
    - ruby_version: "200"
